### ISSUE TITLE
What is the minimum requirement for GPU memory?

### ISSUE THREAD

**Issue by JudgementH** [UCSB-NLP-Chang/Diffusion-SpaceTime-Attn#3]
Hi,
Thanks for your great work!

Could you please provide me with information on the recommended GPU version? Additionally, I would like to know the minimum GPU memory requirement to ensure that my computer system meets the specifications needed to run effectively.

**Comment by wuqiuche** [comment]
Hi JudgementH,

Thank you for your interest to our work! We use one A6000 GPU with 48GB memory. The whole pipeline would need around 45GB memory, where the most memory cost is brought by the attention coefficient optimization for diffusion model.

**Comment by JudgementH** [comment]
Thanks a lot!
