### ISSUE TITLE
Where does mscoco.txt under the datasets floder come from coco2017‘val

### ISSUE THREAD

**Issue by Maybeetw** [UCSB-NLP-Chang/Diffusion-SpaceTime-Attn#7]
Hi there,

Thank you for your amazing work.I would like to ask about the 500 data in mscoco.txt under the datasets folder. These 500 captions are from the raw coco data stuff_ Val.json or caption_ Val.json? It seems like I can't find these 500 texts here, or are these 500 texts from other files in Coco

**Comment by wuqiuche** [comment]
Hi Maybeetw,

Thank you very much for your interests! These captions are from this link in original COCO website: [2017 Train/Val annotations [241MB]](http://images.cocodataset.org/annotations/annotations_trainval2017.zip). 

After downloading, you can find the captions in "captions_train2017.json". For example:
```
import json
with open("captions_train2017.json", "r") as f:
  contents = json.load(f)
caption_0 = contents['annotations'][0]
```
The result should be "A bicycle replica with a clock as the front wheel."

**Comment by Maybeetw** [comment]
Thank you very much for your reply, as the five hundred data were for testing, leading me to think they were from coco_cpation_val or stuff_val,very good job, thanks again for your answer.
