### ISSUE TITLE
About Controlling Attention Mechanisms

### ISSUE THREAD

**Issue by LanTianBy** [UCSB-NLP-Chang/Diffusion-SpaceTime-Attn#8]
Thank you for your contributions!
I am a beginner in the field of computer vision and I am very interested in the content of controlling attention mechanisms in your work. But my code level is average, could you kindly advise me on which files in the directory I should focus on?

**Comment by wuqiuche** [comment]
Hi LanTianBy,

Thank you very much for your interests! Direct to your questions, to see the code for controlling attention mechanisms, the best way is to focus on attention_optimization/stable-diffusion/ldm/models/diffusion/plms.py and attention_optimization/stable-diffusion/ldm/modules/attention.py. 

Specifically: 
1. In "attention_optimization/stable-diffusion/ldm/models/diffusion/plms.py," you may focus on PLMSSampler class. This class defines the sampler needed to generate images and contains our attention optimization process (e.g., PLMSSampler.plms_sampling method).
2. In "attention_optimization/stable-diffusion/ldm/modules/attention.py," you may focus on BasicTransformerBlock class. This is the place where the image-text attention is computed, and it is where the coefficient plays a role in (e.g., BasicTransformerBlock._forward method).

**Comment by LanTianBy** [comment]
> Hi LanTianBy,
> 
> Thank you very much for your interests! Direct to your questions, to see the code for controlling attention mechanisms, the best way is to focus on attention_optimization/stable-diffusion/ldm/models/diffusion/plms.py and attention_optimization/stable-diffusion/ldm/modules/attention.py.
> 
> Specifically:
> 
> 1. In "attention_optimization/stable-diffusion/ldm/models/diffusion/plms.py," you may focus on PLMSSampler class. This class defines the sampler needed to generate images and contains our attention optimization process (e.g., PLMSSampler.plms_sampling method).
> 2. In "attention_optimization/stable-diffusion/ldm/modules/attention.py," you may focus on BasicTransformerBlock class. This is the place where the image-text attention is computed, and it is where the coefficient plays a role in (e.g., BasicTransformerBlock._forward method).

Thank you for your answer, it has been very helpful to me! Thank you again for your work!
